namespace: tutorial
systems:
  db:
    type: postgres
streams:
  users:
    systems:
      db: {}
    schema:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          rngo:
            value: (streams.users.last.id ?? 0) + 1
        full_name:
          type: string
          rngo:
            value: enums.fullNames
        created_at:
          type: string
          format: date-time
          rngo:
            value: sim.now
        roles:
          type: array
          items:
            type: string
            enum:
              - editor
              - buyer
              - engineer
              - exec
      required:
        - id
        - full_name
        - created_at
